//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovic_01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChernovicEntities : DbContext
    {
        private static ChernovicEntities _context;

        public static ChernovicEntities GetContext()
        {
            if (_context == null)
                _context = new ChernovicEntities();
            return _context;
        }
        public ChernovicEntities()
            : base("name=ChernovicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaretialPostvshik> MaretialPostvshik { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Postavshiki> Postavshiki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMaterial> TypeMaterial { get; set; }
        public virtual DbSet<TypePostovshic> TypePostovshic { get; set; }
    }
}
