//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovic_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaretialPostvshik
    {
        public int id { get; set; }
        public int idMaterial { get; set; }
        public int idPostvshik { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Postavshiki Postavshiki { get; set; }
    }
}
