//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chernovic_01
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaretialPostvshik = new HashSet<MaretialPostvshik>();
        }
    
        public int Id { get; set; }
        public string NameMaterial { get; set; }
        public int IdType { get; set; }
        public string Image { get; set; }
        public double Cena { get; set; }
        public int KolNaSklade { get; set; }
        public int MinKol { get; set; }
        public int KolVYpakovke { get; set; }
        public string EdinizeIzmerenia { get; set; }

        public SolidColorBrush Style
        {
            get
            {
                SolidColorBrush myColor = new SolidColorBrush();
                if(KolNaSklade<MinKol)
                {
                    return myColor = (SolidColorBrush)(new BrushConverter().ConvertFrom("#f19292")); ;
                }
                if(KolNaSklade == 3*MinKol)
                {
                    return myColor = (SolidColorBrush)(new BrushConverter().ConvertFrom("#ffba01"));
                }
               else
                return  Brushes.White;
            }
        }

        public string SpisokPostavshic
        {
            get
            {
                string spisok = "Поставщики: ";
                foreach (MaretialPostvshik mP in MaretialPostvshik)
                {
                    spisok += mP.Postavshiki.NamePostavshik + ", ";
                }
                return spisok;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaretialPostvshik> MaretialPostvshik { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
    }
}
